apiVersion: v1
kind: Service
metadata:
  labels:
    app: message-service
  name: message-service
  namespace: default
spec:
  externalIPs:
    - 10.160.2.83
  ports:
    - name: message-service
      port: 8182
      protocol: TCP
      targetPort: 8182
  selector:
    app: message-service
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: message-service-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
        - name: message-service
          image: 10.160.2.83:6110/trip/message-service:latest
          ports:
            - containerPort: 8182
