apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service
  name: user-service
  namespace: default
spec:
  ports:
    - name: user-service
      port: 8181
      protocol: TCP
      targetPort: 8181
  selector:
    app: user-service
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: $image
          ports:
            - containerPort: 8181
