apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-edge-service
  name: user-edge-service
  namespace: default
spec:
  ports:
    - name: user-edge-service
      port: 8183
      protocol: TCP
      targetPort: 8183
  selector:
    app: user-edge-service
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-edge-service-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: user-edge-service
    spec:
      containers:
        - name: user-edge-service
          image: 10.160.2.83:6110/trip/user-edge-service:latest
          ports:
            - containerPort: 8183
